### ISSUE TITLE
All over the place

### ISSUE THREAD

**Issue by marcelklehr** [studieren-ohne-grenzen/sog-ansible#3]
I feel like the current implementation is kind of all over the place, with some roles being dependent on stuff that is added to site.yml as well as on other homemade roles. It would be kind of hard to deploy the different apps to different servers in this state, I think. Then again, I'm not sure if there's any way to improve this

**Comment by zonradkuse** [comment]
I've done some reading on this and there are essentially two ways to resolve this. Either using dependencies on playbook level - which is the way we are currently solving this -  or moving dependencies to `<role>/meta/main.yml` specifying a dependency array. Second has the drawback that we potentially do not understand which role causes a software package to be installed. Best example to illustrate this would be XWiki (when I am done with it). Up to now we specify a tomcat role in the playbook, however we only need tomcat for XWiki, hence, it would make sense moving the dependency there. This makes XWiki responsible for the deployment of tomcat. 

If we do this, we might miss variables to specify since we didn't explicitly think of tomcat as a dependency. We have to make sure that we fail fast here, i.e. we probably shouldn't specify defaults where they are not obvious in order to fail fast because of unspecified variables.

**Comment by marcelklehr** [comment]
Dependencies is one aspect, I agree. Another problem I see is that we manage state similar to how we would do it on the machine directly: one role for nginx and then a config for nginx which needs to consider all apps that need to be exposed by that nginx instance. When deploying Xwiki, we have to change the nginx config, the mysql config, etc. That also means, should we want to move XWiki to a different host then we need to copy all that stuff over, which probably indicates that it should be integrated into the role itself in the first place.

This might tie into what you said above, here:
> If we do this, we might miss variables to specify since we didn't explicitly think of tomcat as a dependency. We have to make sure that we fail fast here, i.e. we probably shouldn't specify defaults where they are not obvious in order to fail fast because of unspecified variables.

**Comment by zonradkuse** [comment]
I added tags to site.yml. This will give us an idea of interdependency. Of course, this doesn't solve the actual 'all over the place' issue, however, in our case this is not easy to solve and we would likely end up calling roles multiple times. I would say we should see the playbook rather as the software-composition of our servers instead of explicit roles one server has. Moving services will be harder, however, before doing so we need to test the setup anyway, and hence we would discover errors from interdependency.
